<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Product>MeetMemo</Product>
    <Company>MeetMemo</Company>
    <Copyright>Copyright (c) 2026 MeetMemo contributors</Copyright>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <Version>0.1.0</Version>
    <NeutralLanguage>ru-RU</NeutralLanguage>
  </PropertyGroup>
</Project>
